src/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as user_views
from .views import CustomerCreateView
from .decorators import unauthenticated_user


urlpatterns = [
    path('profile/', user_views.profile, name='profile'),
    path('register/', user_views.Register, name='signup'),
    path('login/', unauthenticated_user(auth_views.LoginView.as_view(template_name='user/login.html')), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('customer/', CustomerCreateView.as_view(), name='customer'),
]

src/sale/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('', SaleList.as_view(), name='sale-list'), 
    path('create/', SaleCreate.as_view(), name='sale-create'), 

]

src/server/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('inventory/', include('inventory.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pics/profile.jpg',
                              upload_to='profile_pics', null=True, blank=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)




class Customer(models.Model):
    fname = models.CharField(max_length=40)
    lname = models.CharField(max_length=20)
    gmail = models.EmailField(max_length=20)
    phone= models.IntegerField(max_length=13)
    address= models.TextField(max_length=30)
    
    def __str__(self):
        return self.fname

src/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile,Customer


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', ]


class UserProfileUpdate(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image']


class CustomerForm(forms.ModelForm):
    class Meta:
        model= Customer
        fields='__all__'

src/accounts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .decorators import unauthenticated_user
from django.contrib import messages
from .forms import UserRegistrationForm, UserUpdateForm, UserProfileUpdate


@unauthenticated_user
def Register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'{username} Account has been created!')
            return redirect('login')
    else:
        form = UserRegistrationForm()
    return render(request, 'user/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = UserProfileUpdate(
            request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            username = u_form.cleaned_data.get('username')
            messages.success(request, f'{username} profile has been updated!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = UserProfileUpdate(instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'user/profile.html', context)

src/accounts/templates/user/customer.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<center>
    <div class="container" style="margin-top:100px;" >
        <h3><b>Customer Form</b></h3>
<form action="." method="POST" enctype="multipart/form-data" style="margin-top:10px">
    {% csrf_token %}
    <div class="form-group">
        <input type="text" class="form-control underlined" name="fname" id="id_fname"
            placeholder="First Name " style="width: 300px; height: 35px; box-shadow: 3px 3px 3px 3px #E3E3E3;" maxlength="40" required>
    </div>
    <div class="form-group">
        <input type="text" class="form-control underlined" name="lname" id="id_lname"
            placeholder="Last Name " style="width: 300px; height: 35px;  box-shadow: 3px 3px 3px 3px #E3E3E3;" maxlength="20" required>
    </div>
    <div class="form-group">
        <input type="text" class="form-control underlined" name="lname" id="id_gmail"
            placeholder="Gmail " style="width: 300px; height: 35px;  box-shadow: 3px 3px 3px 3px #E3E3E3;" maxlength="20" required>
    </div>
    <div class="form-group">
        <input type="number" class="form-control underlined" name="phone" id="id_phone"
            placeholder="Mobile Number " style="width: 300px; height: 35px;  box-shadow: 3px 3px 3px 3px #E3E3E3;" maxlength="20" required>
    </div>
    <div class="form-group">
        <textarea class="form-control underlined" name="phone" id="id_address"
            placeholder="Address " style="width: 300px; height: 35px;  box-shadow: 3px 3px 3px 3px #E3E3E3;" maxlength="20" cols="40" rows="10" maxlength="30" required></textarea>
    </div>
    <button type="submit"  style="background-color: green; color:white; width: 100px; height: 35px;">submit</button>
 </form>
    </div>
</center>
{% endblock %}

src/accounts/templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static 'homer/vendor/metisMenu/dist/metisMenu.css' %}" />
    <link rel="stylesheet" href="{% static 'homer/vendor/animate.css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'homer/vendor/bootstrap/dist/css/bootstrap.css' %}" />

    <link rel="stylesheet" href="{% static 'homer/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css' %}" />
    <link rel="stylesheet" href="{% static 'homer/fonts/pe-icon-7-stroke/css/helper.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'homer/styles/style.css' %}">

    <style>
        *,
        input:focus,
        button:focus {
            outline: none;
        }
    </style>
    <title>login</title>
</head>

<body class="blank">

    <!-- Simple splash screen-->
    <div class="splash">
        <div class="color-line"></div>
        <div class="splash-title">
            <h1>News Desk</h1>
            <div class="spinner">
                <div class="rect1"></div>
                <div class="rect2"></div>
                <div class="rect3"></div>
                <div class="rect4"></div>
                <div class="rect5"></div>
            </div>
        </div>
    </div>

    <div class="color-line"></div>
    <div class="login-container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center m-b-md">
                    <img src="{% static 'img/channel-logo.jpeg' %}" alt="" width="20%">
                    <h3>PLEASE LOGIN TO News Desk</h3>
                </div>
                <div class="hpanel">
                    <div class="panel-body">
                        <form method="POST" id="loginForm">{% csrf_token %}
                            <div class="form-group">
                                <label class="control-label" for="username">Username</label>
                                <input class="form-control" autocomplete="username" type="text" name="username" required
                                    id="id_username" placeholder="username">
                                <span class="help-block small">Your unique username to app</span>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="password">Password</label>
                                <input class="form-control" autocomplete="new-password" type="password" name="password"
                                    required id="id_password" placeholder="********">
                                <span class="help-block small">Your strong password</span>
                            </div>
                            <button type="submit" class="btn btn-success btn-block">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <strong>ChANNEL</strong> - five pakistan<br /> 2020 Copyright
            </div>
        </div>
    </div>
    <script src="{% static 'homer/vendor/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'homer/vendor/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'homer/vendor/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'homer/vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'homer/vendor/iCheck/icheck.min.js' %}"></script>
    <script src="{% static 'homer/vendor/sparkline/index.js' %}"></script>

</body>

</html>

src/accounts/templates/user/profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block body %}

<div class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-body">
                    <div class="col-md-12 text-center">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="avatar-upload mt-0">
                                <div class="avatar-edit">
                                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
                                    <label for="id_image"></label>
                                </div>
                                <div class="avatar-preview">
                                    <div id="imagePreview"
                                        style="background-image: url('{{ user.profile.image.url }}');">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                {% render_field u_form.username type="text" class="form-control" %}
                            </div>
                            <div class="form-group">
                                {% render_field u_form.email type="text" class="form-control" %}
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<script src="{% static 'homer/vendor/jquery/dist/jquery.min.js' %}"></script>
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#imagePreview').css('background-image', 'url(' + e.target.result + ')');
                $('#imagePreview').hide();
                $('#imagePreview').fadeIn(650);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#id_image").change(function () {
        readURL(this);
    });
</script>

{% endblock %}

src/accounts/templates/user/register.html
{% extends 'user/login.html' %}

{% block body %}
<form class="login-form form-group" method="POST">
    <h1 class="h4 text-center font-weight-normal">Sign in</h1>
    {% csrf_token %}
    <div class="form-group">
        <input type="text" class="form-control" name="username" maxlength="150" id="id_username" autocomplete="nope"
            placeholder="username" required>
    </div>
    <div class="form-group">
        <input type="email" class="form-control" name="email" id="id_email" autocomplete="nope"
            placeholder="your@email.com" required>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password1" id="id_password1" placeholder="password"
            autocomplete="new-password" required>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password2" id="id_password2"
            placeholder="password confirmation" autocomplete="new-password" required>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-block btn-secondary">Register</button>
    </div>
    <small class="text-muted">
        <a class="ml-2" href="{% url 'login' %}">Already have an account?</a>
    </small>
</form>
{% endblock %}